title: OctoCode.
email: info@octocode.org

url: "http://octocode.org"

header_menu:
  - title: Услуги
    url: /service/
  - title: Проекты
    url: /project/
  - title: Вакансии
    url: /job/
  - title: Контакты
    url: /contacts


css:
  - /assets/css/style.css
  - /assets/css/grid.css

permalink: /:categories/:year/:month/:title/

timezone:    Asia/Yekaterinburg
future:      true
highlighter: pygments
markdown:    kramdown
kramdown:
  auto_ids: false
